### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by jdtoms** [ABbiodiversity/cure4insect#38]
In core_functions.Rd, line 123, link is broken

**Comment by psolymos** [comment]
The right base URL is http://sc-dev.abmi.ca/ because the previous server broke down. The link is fixed in the new version which is not public yet (v2018 branch, not merged to master). You can install the new version and set the options to use the 2017 version (2012 footprint inventory) for birds:

``` R
remotes::install_github("ABbiodiversity/cure4insect", ref="v2018")
library(cure4insect)
set_options(version="2017")
```
