### ISSUE TITLE
update upland/lowland column in species table

### ISSUE THREAD

**Issue by psolymos** [ABbiodiversity/cure4insect#46]
upland/lowland classification has `NA`s. @beallen will provide and update.

**Comment by psolymos** [comment]
Thanks @beallen the changes are now incorporated. There are 10 genera that are set to `"NotAssessed"` that were `NA` in the table you provided.

**Comment by beallen** [comment]
@psolymos Six species were given a "NotAssessed" status because they are genus level models, while four species were given that status as they currently have taxonomic issues.
